/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedRunsIndexRouteImport } from './routes/_authenticated/runs.index'
import { Route as AuthenticatedRunsIdRouteImport } from './routes/_authenticated/runs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRunsIndexRoute = AuthenticatedRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRunsIdRoute = AuthenticatedRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/paywall': typeof PaywallRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/runs/$id': typeof AuthenticatedRunsIdRoute
  '/runs/': typeof AuthenticatedRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/paywall': typeof PaywallRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/runs/$id': typeof AuthenticatedRunsIdRoute
  '/runs': typeof AuthenticatedRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/paywall': typeof PaywallRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/runs/$id': typeof AuthenticatedRunsIdRoute
  '/_authenticated/runs/': typeof AuthenticatedRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/paywall' | '/memory' | '/runs/$id' | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/paywall' | '/memory' | '/runs/$id' | '/runs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/paywall'
    | '/_authenticated/memory'
    | '/_authenticated/runs/$id'
    | '/_authenticated/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PaywallRoute: typeof PaywallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runs/': {
      id: '/_authenticated/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthenticatedRunsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runs/$id': {
      id: '/_authenticated/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof AuthenticatedRunsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedRunsIdRoute: typeof AuthenticatedRunsIdRoute
  AuthenticatedRunsIndexRoute: typeof AuthenticatedRunsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedRunsIdRoute: AuthenticatedRunsIdRoute,
  AuthenticatedRunsIndexRoute: AuthenticatedRunsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PaywallRoute: PaywallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
